### ISSUE TITLE
Expose ND proof editor for OLP systems

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#56]
Expose proof checker and editor for Gentzen ND systems, using the syntax and rules used in the OLP.

For rule names right now the convention is *Intro and *Elim (rather than *I and *E)---I could change that and in OLP and it may be a good idea anyway, but if it can easily be done so that the editor accepts both that'd be nice. 

The intuitionistic absurdity (explosion) rule should *not* be ~E. I will make this configurable in OLP and make the standard agree with forall x YYC (that is, X for explosion).

 NK should use classical absurdity rule instead of LEM ie 
```
[~A]
...
!?
------
A
```
The label for this should be IP as in forall X.

**Comment by rzach** [comment]
I could use this in two weeks in my class but no pressure ;)

**Comment by gleachkr** [comment]
Nothing like a deadline... :)

**Comment by gleachkr** [comment]
OK, done with a prototype for the propositional part:

https://carnap.io/shared/gleachkr@gmail.com/OpenLogicND.pandoc

Markup is attached, but other than the system string, it's as in 

https://carnap.io/shared/gleachkr@gmail.com/carnap-gentzen-ND.pandoc

Were you planning on also using this for first-order logic?

Markup here: [OpenLogicND.txt](https://github.com/gleachkr/Carnap/files/4242149/OpenLogicND.txt)

**Comment by rzach** [comment]
Thanks! yes, I was hoping for FOL as well.

**Comment by rzach** [comment]
Here's an issue I noticed: in Prawitz and OLP, vE discharges assumptions in two subproofs, but the convention is to label both assumptions the same, i.e., it's vE (n) and both disjuncts are labelled n.

**Comment by rzach** [comment]
Not sure this is a ProofJS issue or specific to the OLP system, but I'm not able to get a cursor into the endformula of the example proof, so can't edit it.

**Comment by gleachkr** [comment]
Thanks - sounds good. I'll work on getting FOL up, and changing the assumption discharge convention.

Right now, the endformula isn't editable in homework problems. This isn't specifically a ProofJS thing, it's just meant to help keep the goal of the proof in mind for homework problems. Would it be better for this to be editable?

**Comment by rzach** [comment]
Ah I didn't realize that. Seems like maybe you want the students to have to do that themselves, the same way they do for the Fitch proofs?  Maybe make it an option?  

The immediate issue is that if you can't place a cursor into the endformula there is no visual feedback that the end-formula is selected at all, so unless you click there blindly and then press Ctrl-Enter you might not know what to do. Also, it does allow you to add a child node, which then becomes not editable, and that then is a situation you can't recover from.

**Comment by rzach** [comment]
PS https://carnap.io/shared/gleachkr@gmail.com/carnap-gentzen-ND.pandoc switches the meaning of Crtl-Enter and Shift-Ctrl-Enter

**Comment by gleachkr** [comment]
That's all very helpful. Sounds like the immutable endformulas are maybe not the right idea from a UI perspective. I'll fix that. I just pushed an update to get the vE discharge conventions in line with OLP. I'll try to work more on the rest tomorrow.

**Comment by gleachkr** [comment]
OK, I've made endformulas mutable, and done some work on the FOL system. Here's the invocation for the prototype:

    ```{.TreeDeduction system="openLogicFOLNK"}
    1.1 Ax(A(x)->B(x)),ExA(x) :|-: ExB(x)
    ```

Unfortunately, (as you'll probably notice), EE is not working properly. It doesn't discharge assumptions as it should. I basically didn't anticipate exactly how this case (where, roughly, one of the schematic variables of the inference only occurs in assumptions) needed to work. As a result, handling it is going to require some lower level changes to how the tree deduction checker works. I'll get going on this, but I'm a little worried it won't be ready in time for your class...

**Comment by gleachkr** [comment]
OK, I had an idea for a managable (actually not too bad) alternative approach to the problem after posting the above. I think I now have something that is ready for testing. I've deployed the update, so you can use the same invocation as above if you want to try it out.

**Comment by rzach** [comment]
Thanks! I've made a sample page at https://carnap.io/shared/rzach@ucalgary.ca/Practice%20Problems%20ND.md

First of all, since there is no difference in the syntax between propositional and first-order, we can get away with just a single system. (In fact, now that I think of it, that's also the case for ZachTFL2019 and ZachFOL2019!)

Issues  I see:

- [x] Rule labels for negation are not recognized when negation is given as ~ (~I, ~Intro) -- see third example 9.7
- [x] Something's going wrong in 9.6 and 9.7. The IP rule and the ~I rule respectively are correct but it says "assumption mismatch".
- [x] Although the examples contain complete correct proofs (at least in the first case), the top line isn't turning green to indicate the exercise is solved correctly.
- [x] Would be nice to have a "Playground" like for Fitch proofs. I suppose you can use any ProofJS widget to play around in and just hover over the last rule to see what's proved, but still. 
- [x] Make an option to expose the "show JSON" button like the ProofJS example.  (Moved to separate issue #67)
- [x] There should be a warning/error if a rule cites an assumption that isn't labelled (see Ex 9.6: the last IP inference cites assumption (1) but there is no assumption (1))
- [x] Something's odd about discharging assumptions by IP. In Ex 9.6, if you discharge the top left assumption ~(A \/ ~A) by adding a parent node and label the rule (1), then hover over the final inference label, it still shows `¬(A ∨ ¬A) ⊢ (A ∨ ¬A)`
- [x] Parsed & displays formulas (eg in the top box) should suppress outermost parentheses.
- [x] Add =E and =I rules.

**Comment by rzach** [comment]
PS not sure where this should go but would prefer outermost parentheses of formulas suppressed.

**Comment by gleachkr** [comment]
The first two bullets should now be fixed. I'll keep working on the rest. Thanks for all the testing!

**Comment by rzach** [comment]
Awesome thanks! I found two more issues and added them above.

**Comment by gleachkr** [comment]
OK, I've deployed something for suppressing outermost parentheses, and for giving a visual indication when the proof is finished.

I'm not sure I understand the issue with 9.6 - I do get that sequent when I discharge the top left assumption, but I think that's because of the other place where the same formula is assumed. When I discharge both, currently, it seems to be functioning correctly. Am I missing something?

**Comment by rzach** [comment]
No you're not I missed the second open assumption.

**Comment by rzach** [comment]
In the last 4 problems on that page, I just say what they should prove and Carnap puts in the endformula itself. There we still have the outermost parentheses. (Not a priority of course)

**Comment by gleachkr** [comment]
OK, playgrounds are implemented. These are creted with `.TreePlayground` rather than `.TreeDeduction`, so one might look like this:

    ```{.TreePlayground .openLogicNK}
    OPTIONALJSONHERE
    ```

I also took up your suggestion from earlier to make prepopulating the endformula optional. It's now hidden behind the option `prepopulate`, so you'd set `options="prepopulate"`. There's also now some coloring to make the empty endformula input a little easier to spot.

**Comment by rzach** [comment]
Ooh cool thanks!

**Comment by rzach** [comment]
Does it handle = yet?

**Comment by gleachkr** [comment]
Doesn't handle = yet, but that should be easy to add.

**Comment by rzach** [comment]
I've made issue #67 for the "show me the JSON" functionality, which isn't really specific to OLP ND support. So once = is added and maybe you merge the `openLogicNK` and `openLogicFOLNK` into a single system (as noted above) this is done.

**Comment by rzach** [comment]
One more thing that's odd: If a rule cites an assumption to discharge but doesn't put it in parentheses, the assumption remains undischarged but Carnap also doesn't complain that there's an error. Perhaps the nice thing to do would be to accept discharge labels both with and without parentheses if that's easy. 
See last inference:
![image](https://user-images.githubusercontent.com/3122348/76009414-65a7ef80-5ece-11ea-8da2-69bc617e7419.png)

**Comment by rzach** [comment]
I can totally live without it but: OLP allows t≠s as an abbreviation of ~t=s. How hard would it be to allow this (ie allow say `x!=y` as a formula and accept `x!=y` and `x=y` as premises to `~E`)?

**Comment by gleachkr** [comment]
Would the idea be that `x != y` should parse as ¬(x = y)? Or would it be to introduce a new symbol into the language? I think the former would be pretty straightforward, the latter might be more involved.

**Comment by rzach** [comment]
The former. If the formula parser can do that it would be ideal since then  the model checker/symbolization checker would work with it too?

**Comment by gleachkr** [comment]
Yep! OK, I'll add that to the Calgary 2019 parser, if that's OK.

**Comment by rzach** [comment]
Yes that'd be ok. Is that what the OLP proof thing works with?

**Comment by gleachkr** [comment]
Yep, they both use the same formula parser (it'd be possible to split them, but this seemed the most straightforward).

**Comment by gleachkr** [comment]
OK, I've just deployed some updates that add the = rules, update parsing to handle `!=` as shorthand for a negated equality, and  to allow both (1) and 1 as assumption references, while disallowing junk other than whitespace at the end of the rule citation (the problem previously was that the rule-label parser was happy to discard the tail end of a string, as long as it could parse an initial segment).

**Comment by rzach** [comment]
Amazing, thank you!

**Comment by rzach** [comment]
One tiny thing: can it also parse `≠`? Want a separate issue for that?

**Comment by gleachkr** [comment]
Ah right. No, it's ok. Should just take a minute.

**Comment by gleachkr** [comment]
OK, `≠` now also parses.
